apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9deploy
spec:
  strategy:
    type: RollingUpdate
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: aws9ctn
        image: jsjs22lee/aws9:blue
---
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc
spec:
  type: NodePort
  ports:
  - name: aws9-port
    port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: web